fragment HomeParts on Home {
  intro
}

fragment AboutParts on About {
  title
  body
  overallWebSkills {
    __typename
    name
    percentage
    color
  }
  frontend
  backend
  generalCoding
  others
}

fragment PostParts on Post {
  title
  postDateTime
  tags
  excerpt
  body
}
